# generated by datamodel-codegen:
#   filename:  parameters.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, RootModel


class Model(RootModel[Any]):
    root: Any


class LegoColorsListParameters(BaseModel):
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None


class LegoColorsReadParameters(BaseModel):
    id: str
    ordering: str | None = None


class LegoElementsReadParameters(BaseModel):
    element_id: str


class LegoMinifigsListParameters(BaseModel):
    in_set_num: str | None = None
    in_theme_id: str | None = None
    max_parts: float | None = None
    min_parts: float | None = None
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    search: str | None = None


class LegoMinifigsPartsListParameters(BaseModel):
    page: int | None = None
    page_size: int | None = None
    set_num: str


class LegoMinifigsReadParameters(BaseModel):
    set_num: str


class LegoMinifigsSetsListParameters(BaseModel):
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    set_num: str


class LegoPartCategoriesListParameters(BaseModel):
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None


class LegoPartCategoriesReadParameters(BaseModel):
    id: int
    ordering: str | None = None


class LegoPartsColorsListParameters(BaseModel):
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    part_num: str


class LegoPartsColorsReadParameters(BaseModel):
    color_id: str
    part_num: str


class LegoPartsColorsSetsListParameters(BaseModel):
    color_id: str
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    part_num: str


class LegoPartsListParameters(BaseModel):
    bricklink_id: str | None = None
    brickowl_id: str | None = None
    color_id: str | None = None
    inc_part_details: bool | None = None
    ldraw_id: str | None = None
    lego_id: str | None = None
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    part_cat_id: str | None = None
    part_num: str | None = None
    part_nums: str | None = None
    search: str | None = None


class LegoPartsReadParameters(BaseModel):
    inc_part_details: bool | None = None
    part_num: str


class LegoSetsAlternatesListParameters(BaseModel):
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    set_num: str


class LegoSetsListParameters(BaseModel):
    max_parts: float | None = None
    max_year: float | None = None
    min_parts: float | None = None
    min_year: float | None = None
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    search: str | None = None
    theme_id: str | None = None


class LegoSetsMinifigsListParameters(BaseModel):
    page: int | None = None
    page_size: int | None = None
    set_num: str


class LegoSetsPartsListParameters(BaseModel):
    inc_color_details: bool | None = None
    inc_minifig_parts: bool | None = None
    inc_part_details: bool | None = None
    page: int | None = None
    page_size: int | None = None
    set_num: str


class LegoSetsReadParameters(BaseModel):
    set_num: str


class LegoSetsSetsListParameters(BaseModel):
    page: int | None = None
    page_size: int | None = None
    set_num: str


class LegoThemesListParameters(BaseModel):
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None


class LegoThemesReadParameters(BaseModel):
    id: int
    ordering: str | None = None


class SwaggerListParameters(BaseModel):
    pass


class UsersTokenCreateParameters(BaseModel):
    password: str = Field(repr=False)
    username: str


class UsersAllpartsListParameters(BaseModel):
    color_id: float | None = None
    inc_part_details: bool | None = None
    page: int | None = None
    page_size: int | None = None
    part_cat_id: float | None = None
    part_num: str | None = None
    user_token: str = Field(repr=False)


class UsersBadgesListParameters(BaseModel):
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None


class UsersBadgesReadParameters(BaseModel):
    id: int
    ordering: str | None = None


class UsersBuildReadParameters(BaseModel):
    set_num: str
    user_token: str = Field(repr=False)


class UsersLostPartsCreateParameters(BaseModel):
    inv_part_id: int
    lost_quantity: int | None = None
    user_token: str = Field(repr=False)


class UsersLostPartsDeleteParameters(BaseModel):
    id: str
    ordering: str | None = None
    user_token: str = Field(repr=False)


class UsersLostPartsListParameters(BaseModel):
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    user_token: str = Field(repr=False)


class UsersMinifigsListParameters(BaseModel):
    fig_set_num: str | None = None
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    search: str | None = None
    user_token: str = Field(repr=False)


class UsersPartlistsCreateParameters(BaseModel):
    is_buildable: bool | None = None
    name: str
    num_parts: int | None = None
    user_token: str = Field(repr=False)


class UsersPartlistsDeleteParameters(BaseModel):
    list_id: str
    user_token: str = Field(repr=False)


class UsersPartlistsListParameters(BaseModel):
    page: int | None = None
    page_size: int | None = None
    user_token: str = Field(repr=False)


class UsersPartlistsPartialUpdateParameters(BaseModel):
    is_buildable: bool | None = None
    list_id: str
    name: str | None = None
    num_parts: int | None = None
    user_token: str = Field(repr=False)


class UsersPartlistsPartsCreateParameters(BaseModel):
    color_id: int
    list_id: str
    part_num: str
    quantity: int
    user_token: str = Field(repr=False)


class UsersPartlistsPartsDeleteParameters(BaseModel):
    color_id: str
    list_id: str
    ordering: str | None = None
    part_num: str
    user_token: str = Field(repr=False)


class UsersPartlistsPartsListParameters(BaseModel):
    inc_color_details: bool | None = None
    inc_part_details: bool | None = None
    list_id: str
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    user_token: str = Field(repr=False)


class UsersPartlistsPartsReadParameters(BaseModel):
    color_id: str
    list_id: str
    ordering: str | None = None
    part_num: str
    user_token: str = Field(repr=False)


class UsersPartlistsPartsUpdateParameters(BaseModel):
    color_id: str
    list_id: str
    ordering: str | None = None
    part_num: str
    quantity: int
    user_token: str = Field(repr=False)


class UsersPartlistsReadParameters(BaseModel):
    list_id: str
    user_token: str = Field(repr=False)


class UsersPartlistsUpdateParameters(BaseModel):
    is_buildable: bool | None = None
    list_id: str
    name: str
    num_parts: int | None = None
    user_token: str = Field(repr=False)


class UsersPartsListParameters(BaseModel):
    color_id: float | None = None
    inc_part_details: bool | None = None
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    part_cat_id: float | None = None
    part_num: str | None = None
    search: str | None = None
    user_token: str = Field(repr=False)


class UsersProfileReadParameters(BaseModel):
    user_token: str = Field(repr=False)


class UsersSetlistsCreateParameters(BaseModel):
    is_buildable: bool | None = None
    name: str
    num_sets: int | None = None
    user_token: str = Field(repr=False)


class UsersSetlistsDeleteParameters(BaseModel):
    list_id: str
    user_token: str = Field(repr=False)


class UsersSetlistsListParameters(BaseModel):
    page: int | None = None
    page_size: int | None = None
    user_token: str = Field(repr=False)


class UsersSetlistsPartialUpdateParameters(BaseModel):
    is_buildable: bool | None = None
    list_id: str
    name: str | None = None
    num_sets: int | None = None
    user_token: str = Field(repr=False)


class UsersSetlistsReadParameters(BaseModel):
    list_id: str
    user_token: str = Field(repr=False)


class UsersSetlistsSetsCreateParameters(BaseModel):
    include_spares: bool | None = None
    list_id: str
    quantity: int | None = None
    set_num: str
    user_token: str = Field(repr=False)


class UsersSetlistsSetsDeleteParameters(BaseModel):
    list_id: str
    ordering: str | None = None
    set_num: str
    user_token: str = Field(repr=False)


class UsersSetlistsSetsListParameters(BaseModel):
    list_id: str
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    user_token: str = Field(repr=False)


class UsersSetlistsSetsPartialUpdateParameters(BaseModel):
    include_spares: bool | None = None
    list_id: str
    ordering: str | None = None
    quantity: int | None = None
    set_num: str
    user_token: str = Field(repr=False)


class UsersSetlistsSetsReadParameters(BaseModel):
    list_id: str
    ordering: str | None = None
    set_num: str
    user_token: str = Field(repr=False)


class UsersSetlistsSetsUpdateParameters(BaseModel):
    include_spares: bool | None = None
    list_id: str
    ordering: str | None = None
    quantity: int | None = None
    set_num: str
    user_token: str = Field(repr=False)


class UsersSetlistsUpdateParameters(BaseModel):
    is_buildable: bool | None = None
    list_id: str
    name: str
    num_sets: int | None = None
    user_token: str = Field(repr=False)


class UsersSetsCreateParameters(BaseModel):
    include_spares: bool | None = None
    quantity: int | None = None
    set_num: str
    user_token: str = Field(repr=False)


class UsersSetsDeleteParameters(BaseModel):
    max_parts: float | None = None
    max_year: float | None = None
    min_parts: float | None = None
    min_year: float | None = None
    ordering: str | None = None
    search: str | None = None
    set_num: str
    theme_id: float | None = None
    user_token: str = Field(repr=False)


class UsersSetsListParameters(BaseModel):
    max_parts: float | None = None
    max_year: float | None = None
    min_parts: float | None = None
    min_year: float | None = None
    ordering: str | None = None
    page: int | None = None
    page_size: int | None = None
    search: str | None = None
    set_num: str | None = None
    theme_id: float | None = None
    user_token: str = Field(repr=False)


class UsersSetsReadParameters(BaseModel):
    max_parts: float | None = None
    max_year: float | None = None
    min_parts: float | None = None
    min_year: float | None = None
    ordering: str | None = None
    search: str | None = None
    set_num: str
    theme_id: float | None = None
    user_token: str = Field(repr=False)


class UsersSetsSyncCreateParameters(BaseModel):
    include_spares: bool | None = None
    quantity: int | None = None
    set_num: str
    user_token: str = Field(repr=False)


class UsersSetsUpdateParameters(BaseModel):
    max_parts: float | None = None
    max_year: float | None = None
    min_parts: float | None = None
    min_year: float | None = None
    ordering: str | None = None
    quantity: int | None = None
    search: str | None = None
    set_num: str
    theme_id: float | None = None
    user_token: str = Field(repr=False)
