"""Generated from the vendored Rebrickable Swagger document."""

from dataclasses import dataclass
from typing import Any

OPENAPI_SHA256 = "91b49e310f8fb2db4ff7474e2775921897e10319a71ec053cac61f3a40fa7cb6"


@dataclass(frozen=True, slots=True)
class Parameter:
    name: str
    location: str
    schema_type: str
    required: bool
    default: Any | None
    description: str


@dataclass(frozen=True, slots=True)
class Operation:
    method: str
    path: str
    path_parameters: tuple[str, ...]
    query_parameters: tuple[str, ...]
    form_parameters: tuple[str, ...]
    required_parameters: tuple[str, ...]
    encoding: str | None
    parameter_details: tuple[Parameter, ...]


OPERATIONS: dict[str, Operation] = {
    "lego_colors_list": Operation(
        "GET",
        "/lego/colors/",
        (),
        ("page", "page_size", "ordering"),
        (),
        (),
        None,
        (
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "lego_colors_read": Operation(
        "GET",
        "/lego/colors/{id}/",
        ("id",),
        ("ordering",),
        (),
        ("id",),
        None,
        (
            Parameter(
                "id",
                "path",
                "string",
                True,
                None,
                "A unique value identifying this color.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "lego_elements_read": Operation(
        "GET",
        "/lego/elements/{element_id}/",
        ("element_id",),
        (),
        (),
        ("element_id",),
        None,
        (Parameter("element_id", "path", "string", True, None, ""),),
    ),
    "lego_minifigs_list": Operation(
        "GET",
        "/lego/minifigs/",
        (),
        (
            "page",
            "page_size",
            "min_parts",
            "max_parts",
            "in_set_num",
            "in_theme_id",
            "ordering",
            "search",
        ),
        (),
        (),
        None,
        (
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter("min_parts", "query", "number", False, None, ""),
            Parameter("max_parts", "query", "number", False, None, ""),
            Parameter("in_set_num", "query", "string", False, None, ""),
            Parameter("in_theme_id", "query", "string", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter("search", "query", "string", False, None, "A search term."),
        ),
    ),
    "lego_minifigs_read": Operation(
        "GET",
        "/lego/minifigs/{set_num}/",
        ("set_num",),
        (),
        (),
        ("set_num",),
        None,
        (Parameter("set_num", "path", "string", True, None, ""),),
    ),
    "lego_minifigs_parts_list": Operation(
        "GET",
        "/lego/minifigs/{set_num}/parts/",
        ("set_num",),
        ("page", "page_size"),
        (),
        ("set_num",),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
        ),
    ),
    "lego_minifigs_sets_list": Operation(
        "GET",
        "/lego/minifigs/{set_num}/sets/",
        ("set_num",),
        ("page", "page_size", "ordering"),
        (),
        ("set_num",),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "lego_part_categories_list": Operation(
        "GET",
        "/lego/part_categories/",
        (),
        ("page", "page_size", "ordering"),
        (),
        (),
        None,
        (
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "lego_part_categories_read": Operation(
        "GET",
        "/lego/part_categories/{id}/",
        ("id",),
        ("ordering",),
        (),
        ("id",),
        None,
        (
            Parameter(
                "id",
                "path",
                "integer",
                True,
                None,
                "A unique integer value identifying this part category.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "lego_parts_list": Operation(
        "GET",
        "/lego/parts/",
        (),
        (
            "page",
            "page_size",
            "part_num",
            "part_nums",
            "part_cat_id",
            "color_id",
            "bricklink_id",
            "brickowl_id",
            "lego_id",
            "ldraw_id",
            "ordering",
            "search",
            "inc_part_details",
        ),
        (),
        (),
        None,
        (
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter("part_num", "query", "string", False, None, ""),
            Parameter("part_nums", "query", "string", False, None, ""),
            Parameter("part_cat_id", "query", "string", False, None, ""),
            Parameter("color_id", "query", "string", False, None, ""),
            Parameter("bricklink_id", "query", "string", False, None, ""),
            Parameter("brickowl_id", "query", "string", False, None, ""),
            Parameter("lego_id", "query", "string", False, None, ""),
            Parameter("ldraw_id", "query", "string", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter("search", "query", "string", False, None, "A search term."),
            Parameter(
                "inc_part_details",
                "query",
                "boolean",
                False,
                None,
                "Compatibility parameter",
            ),
        ),
    ),
    "lego_parts_read": Operation(
        "GET",
        "/lego/parts/{part_num}/",
        ("part_num",),
        ("inc_part_details",),
        (),
        ("part_num",),
        None,
        (
            Parameter("part_num", "path", "string", True, None, ""),
            Parameter(
                "inc_part_details",
                "query",
                "boolean",
                False,
                None,
                "Compatibility parameter",
            ),
        ),
    ),
    "lego_parts_colors_list": Operation(
        "GET",
        "/lego/parts/{part_num}/colors/",
        ("part_num",),
        ("page", "page_size", "ordering"),
        (),
        ("part_num",),
        None,
        (
            Parameter("part_num", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "lego_parts_colors_read": Operation(
        "GET",
        "/lego/parts/{part_num}/colors/{color_id}/",
        ("part_num", "color_id"),
        (),
        (),
        ("part_num", "color_id"),
        None,
        (
            Parameter("part_num", "path", "string", True, None, ""),
            Parameter("color_id", "path", "string", True, None, ""),
        ),
    ),
    "lego_parts_colors_sets_list": Operation(
        "GET",
        "/lego/parts/{part_num}/colors/{color_id}/sets/",
        ("part_num", "color_id"),
        ("page", "page_size", "ordering"),
        (),
        ("part_num", "color_id"),
        None,
        (
            Parameter("part_num", "path", "string", True, None, ""),
            Parameter("color_id", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "lego_sets_list": Operation(
        "GET",
        "/lego/sets/",
        (),
        (
            "page",
            "page_size",
            "theme_id",
            "min_year",
            "max_year",
            "min_parts",
            "max_parts",
            "ordering",
            "search",
        ),
        (),
        (),
        None,
        (
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter("theme_id", "query", "string", False, None, ""),
            Parameter("min_year", "query", "number", False, None, ""),
            Parameter("max_year", "query", "number", False, None, ""),
            Parameter("min_parts", "query", "number", False, None, ""),
            Parameter("max_parts", "query", "number", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter("search", "query", "string", False, None, "A search term."),
        ),
    ),
    "lego_sets_read": Operation(
        "GET",
        "/lego/sets/{set_num}/",
        ("set_num",),
        (),
        (),
        ("set_num",),
        None,
        (Parameter("set_num", "path", "string", True, None, ""),),
    ),
    "lego_sets_alternates_list": Operation(
        "GET",
        "/lego/sets/{set_num}/alternates/",
        ("set_num",),
        ("page", "page_size", "ordering"),
        (),
        ("set_num",),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "lego_sets_minifigs_list": Operation(
        "GET",
        "/lego/sets/{set_num}/minifigs/",
        ("set_num",),
        ("page", "page_size"),
        (),
        ("set_num",),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
        ),
    ),
    "lego_sets_parts_list": Operation(
        "GET",
        "/lego/sets/{set_num}/parts/",
        ("set_num",),
        (
            "page",
            "page_size",
            "inc_part_details",
            "inc_color_details",
            "inc_minifig_parts",
        ),
        (),
        ("set_num",),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "inc_part_details",
                "query",
                "boolean",
                False,
                None,
                "Compatibility parameter",
            ),
            Parameter(
                "inc_color_details",
                "query",
                "boolean",
                False,
                None,
                "Compatibility parameter",
            ),
            Parameter(
                "inc_minifig_parts",
                "query",
                "boolean",
                False,
                None,
                "Compatibility parameter",
            ),
        ),
    ),
    "lego_sets_sets_list": Operation(
        "GET",
        "/lego/sets/{set_num}/sets/",
        ("set_num",),
        ("page", "page_size"),
        (),
        ("set_num",),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
        ),
    ),
    "lego_themes_list": Operation(
        "GET",
        "/lego/themes/",
        (),
        ("page", "page_size", "ordering"),
        (),
        (),
        None,
        (
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "lego_themes_read": Operation(
        "GET",
        "/lego/themes/{id}/",
        ("id",),
        ("ordering",),
        (),
        ("id",),
        None,
        (
            Parameter(
                "id",
                "path",
                "integer",
                True,
                None,
                "A unique integer value identifying this theme.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "swagger_list": Operation("GET", "/swagger/", (), (), (), (), None, ()),
    "users__token_create": Operation(
        "POST",
        "/users/_token/",
        (),
        (),
        ("username", "password"),
        ("username", "password"),
        "application/x-www-form-urlencoded",
        (
            Parameter(
                "username",
                "formData",
                "string",
                True,
                None,
                "Username (or email) of user",
            ),
            Parameter("password", "formData", "string", True, None, "Password of user"),
        ),
    ),
    "users_badges_list": Operation(
        "GET",
        "/users/badges/",
        (),
        ("page", "page_size", "ordering"),
        (),
        (),
        None,
        (
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_badges_read": Operation(
        "GET",
        "/users/badges/{id}/",
        ("id",),
        ("ordering",),
        (),
        ("id",),
        None,
        (
            Parameter(
                "id",
                "path",
                "integer",
                True,
                None,
                "A unique integer value identifying this badge.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_allparts_list": Operation(
        "GET",
        "/users/{user_token}/allparts/",
        ("user_token",),
        (
            "page",
            "page_size",
            "part_num",
            "part_cat_id",
            "color_id",
            "inc_part_details",
        ),
        (),
        ("user_token",),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter("part_num", "query", "string", False, None, ""),
            Parameter("part_cat_id", "query", "number", False, None, ""),
            Parameter("color_id", "query", "number", False, None, ""),
            Parameter(
                "inc_part_details",
                "query",
                "boolean",
                False,
                None,
                "Compatibility parameter",
            ),
        ),
    ),
    "users_build_read": Operation(
        "GET",
        "/users/{user_token}/build/{set_num}/",
        ("set_num", "user_token"),
        (),
        (),
        ("set_num", "user_token"),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
        ),
    ),
    "users_lost_parts_list": Operation(
        "GET",
        "/users/{user_token}/lost_parts/",
        ("user_token",),
        ("page", "page_size", "ordering"),
        (),
        ("user_token",),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_lost_parts_create": Operation(
        "POST",
        "/users/{user_token}/lost_parts/",
        ("user_token",),
        (),
        ("lost_quantity", "inv_part_id"),
        ("user_token", "inv_part_id"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("lost_quantity", "formData", "integer", False, None, ""),
            Parameter("inv_part_id", "formData", "integer", True, None, ""),
        ),
    ),
    "users_lost_parts_delete": Operation(
        "DELETE",
        "/users/{user_token}/lost_parts/{id}/",
        ("user_token", "id"),
        ("ordering",),
        (),
        ("user_token", "id"),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("id", "path", "string", True, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_minifigs_list": Operation(
        "GET",
        "/users/{user_token}/minifigs/",
        ("user_token",),
        ("page", "page_size", "fig_set_num", "ordering", "search"),
        (),
        ("user_token",),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter("fig_set_num", "query", "string", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter("search", "query", "string", False, None, "A search term."),
        ),
    ),
    "users_partlists_list": Operation(
        "GET",
        "/users/{user_token}/partlists/",
        ("user_token",),
        ("page", "page_size"),
        (),
        ("user_token",),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
        ),
    ),
    "users_partlists_create": Operation(
        "POST",
        "/users/{user_token}/partlists/",
        ("user_token",),
        (),
        ("is_buildable", "name", "num_parts"),
        ("user_token", "name"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("is_buildable", "formData", "boolean", False, None, ""),
            Parameter("name", "formData", "string", True, None, ""),
            Parameter("num_parts", "formData", "integer", False, None, ""),
        ),
    ),
    "users_partlists_read": Operation(
        "GET",
        "/users/{user_token}/partlists/{list_id}/",
        ("user_token", "list_id"),
        (),
        (),
        ("user_token", "list_id"),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
        ),
    ),
    "users_partlists_update": Operation(
        "PUT",
        "/users/{user_token}/partlists/{list_id}/",
        ("user_token", "list_id"),
        (),
        ("is_buildable", "name", "num_parts"),
        ("user_token", "list_id", "name"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter("is_buildable", "formData", "boolean", False, None, ""),
            Parameter("name", "formData", "string", True, None, ""),
            Parameter("num_parts", "formData", "integer", False, None, ""),
        ),
    ),
    "users_partlists_partial_update": Operation(
        "PATCH",
        "/users/{user_token}/partlists/{list_id}/",
        ("user_token", "list_id"),
        (),
        ("is_buildable", "name", "num_parts"),
        ("user_token", "list_id"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter("is_buildable", "formData", "boolean", False, None, ""),
            Parameter("name", "formData", "string", False, None, ""),
            Parameter("num_parts", "formData", "integer", False, None, ""),
        ),
    ),
    "users_partlists_delete": Operation(
        "DELETE",
        "/users/{user_token}/partlists/{list_id}/",
        ("user_token", "list_id"),
        (),
        (),
        ("user_token", "list_id"),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
        ),
    ),
    "users_partlists_parts_list": Operation(
        "GET",
        "/users/{user_token}/partlists/{list_id}/parts/",
        ("user_token", "list_id"),
        ("page", "page_size", "ordering", "inc_part_details", "inc_color_details"),
        (),
        ("user_token", "list_id"),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter(
                "inc_part_details",
                "query",
                "boolean",
                False,
                None,
                "Compatibility parameter",
            ),
            Parameter(
                "inc_color_details",
                "query",
                "boolean",
                False,
                None,
                "Compatibility parameter",
            ),
        ),
    ),
    "users_partlists_parts_create": Operation(
        "POST",
        "/users/{user_token}/partlists/{list_id}/parts/",
        ("user_token", "list_id"),
        (),
        ("part_num", "quantity", "color_id"),
        ("user_token", "list_id", "part_num", "quantity", "color_id"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter("part_num", "formData", "string", True, None, ""),
            Parameter("quantity", "formData", "integer", True, None, ""),
            Parameter("color_id", "formData", "integer", True, None, ""),
        ),
    ),
    "users_partlists_parts_read": Operation(
        "GET",
        "/users/{user_token}/partlists/{list_id}/parts/{part_num}/{color_id}/",
        ("part_num", "color_id", "user_token", "list_id"),
        ("ordering",),
        (),
        ("part_num", "color_id", "user_token", "list_id"),
        None,
        (
            Parameter("part_num", "path", "string", True, None, ""),
            Parameter("color_id", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_partlists_parts_update": Operation(
        "PUT",
        "/users/{user_token}/partlists/{list_id}/parts/{part_num}/{color_id}/",
        ("part_num", "color_id", "user_token", "list_id"),
        ("ordering",),
        ("quantity",),
        ("part_num", "color_id", "user_token", "list_id", "quantity"),
        "application/x-www-form-urlencoded",
        (
            Parameter("part_num", "path", "string", True, None, ""),
            Parameter("color_id", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter("quantity", "formData", "integer", True, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_partlists_parts_delete": Operation(
        "DELETE",
        "/users/{user_token}/partlists/{list_id}/parts/{part_num}/{color_id}/",
        ("part_num", "color_id", "user_token", "list_id"),
        ("ordering",),
        (),
        ("part_num", "color_id", "user_token", "list_id"),
        None,
        (
            Parameter("part_num", "path", "string", True, None, ""),
            Parameter("color_id", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_parts_list": Operation(
        "GET",
        "/users/{user_token}/parts/",
        ("user_token",),
        (
            "page",
            "page_size",
            "part_num",
            "part_cat_id",
            "color_id",
            "ordering",
            "search",
            "inc_part_details",
        ),
        (),
        ("user_token",),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter("part_num", "query", "string", False, None, ""),
            Parameter("part_cat_id", "query", "number", False, None, ""),
            Parameter("color_id", "query", "number", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter("search", "query", "string", False, None, "A search term."),
            Parameter(
                "inc_part_details",
                "query",
                "boolean",
                False,
                None,
                "Compatibility parameter",
            ),
        ),
    ),
    "users_profile_read": Operation(
        "GET",
        "/users/{user_token}/profile/",
        ("user_token",),
        (),
        (),
        ("user_token",),
        None,
        (Parameter("user_token", "path", "string", True, None, ""),),
    ),
    "users_setlists_list": Operation(
        "GET",
        "/users/{user_token}/setlists/",
        ("user_token",),
        ("page", "page_size"),
        (),
        ("user_token",),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
        ),
    ),
    "users_setlists_create": Operation(
        "POST",
        "/users/{user_token}/setlists/",
        ("user_token",),
        (),
        ("is_buildable", "name", "num_sets"),
        ("user_token", "name"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("is_buildable", "formData", "boolean", False, None, ""),
            Parameter("name", "formData", "string", True, None, ""),
            Parameter("num_sets", "formData", "integer", False, None, ""),
        ),
    ),
    "users_setlists_read": Operation(
        "GET",
        "/users/{user_token}/setlists/{list_id}/",
        ("user_token", "list_id"),
        (),
        (),
        ("user_token", "list_id"),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
        ),
    ),
    "users_setlists_update": Operation(
        "PUT",
        "/users/{user_token}/setlists/{list_id}/",
        ("user_token", "list_id"),
        (),
        ("is_buildable", "name", "num_sets"),
        ("user_token", "list_id", "name"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter("is_buildable", "formData", "boolean", False, None, ""),
            Parameter("name", "formData", "string", True, None, ""),
            Parameter("num_sets", "formData", "integer", False, None, ""),
        ),
    ),
    "users_setlists_partial_update": Operation(
        "PATCH",
        "/users/{user_token}/setlists/{list_id}/",
        ("user_token", "list_id"),
        (),
        ("is_buildable", "name", "num_sets"),
        ("user_token", "list_id"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter("is_buildable", "formData", "boolean", False, None, ""),
            Parameter("name", "formData", "string", False, None, ""),
            Parameter("num_sets", "formData", "integer", False, None, ""),
        ),
    ),
    "users_setlists_delete": Operation(
        "DELETE",
        "/users/{user_token}/setlists/{list_id}/",
        ("user_token", "list_id"),
        (),
        (),
        ("user_token", "list_id"),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
        ),
    ),
    "users_setlists_sets_list": Operation(
        "GET",
        "/users/{user_token}/setlists/{list_id}/sets/",
        ("user_token", "list_id"),
        ("page", "page_size", "ordering"),
        (),
        ("user_token", "list_id"),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_setlists_sets_create": Operation(
        "POST",
        "/users/{user_token}/setlists/{list_id}/sets/",
        ("user_token", "list_id"),
        (),
        ("set_num", "quantity", "include_spares"),
        ("user_token", "list_id", "set_num"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter("set_num", "formData", "string", True, None, ""),
            Parameter("quantity", "formData", "integer", False, None, ""),
            Parameter("include_spares", "formData", "boolean", False, None, ""),
        ),
    ),
    "users_setlists_sets_read": Operation(
        "GET",
        "/users/{user_token}/setlists/{list_id}/sets/{set_num}/",
        ("set_num", "user_token", "list_id"),
        ("ordering",),
        (),
        ("set_num", "user_token", "list_id"),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_setlists_sets_update": Operation(
        "PUT",
        "/users/{user_token}/setlists/{list_id}/sets/{set_num}/",
        ("set_num", "user_token", "list_id"),
        ("ordering",),
        ("quantity", "include_spares"),
        ("set_num", "user_token", "list_id"),
        "application/x-www-form-urlencoded",
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter("quantity", "formData", "integer", False, None, ""),
            Parameter("include_spares", "formData", "boolean", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_setlists_sets_partial_update": Operation(
        "PATCH",
        "/users/{user_token}/setlists/{list_id}/sets/{set_num}/",
        ("set_num", "user_token", "list_id"),
        ("ordering",),
        ("quantity", "include_spares"),
        ("set_num", "user_token", "list_id"),
        "application/x-www-form-urlencoded",
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter("quantity", "formData", "integer", False, None, ""),
            Parameter("include_spares", "formData", "boolean", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_setlists_sets_delete": Operation(
        "DELETE",
        "/users/{user_token}/setlists/{list_id}/sets/{set_num}/",
        ("set_num", "user_token", "list_id"),
        ("ordering",),
        (),
        ("set_num", "user_token", "list_id"),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("list_id", "path", "string", True, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
        ),
    ),
    "users_sets_list": Operation(
        "GET",
        "/users/{user_token}/sets/",
        ("user_token",),
        (
            "page",
            "page_size",
            "set_num",
            "theme_id",
            "min_year",
            "max_year",
            "min_parts",
            "max_parts",
            "ordering",
            "search",
        ),
        (),
        ("user_token",),
        None,
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter(
                "page",
                "query",
                "integer",
                False,
                None,
                "A page number within the paginated result set.",
            ),
            Parameter(
                "page_size",
                "query",
                "integer",
                False,
                None,
                "Number of results to return per page.",
            ),
            Parameter("set_num", "query", "string", False, None, ""),
            Parameter("theme_id", "query", "number", False, None, ""),
            Parameter("min_year", "query", "number", False, None, ""),
            Parameter("max_year", "query", "number", False, None, ""),
            Parameter("min_parts", "query", "number", False, None, ""),
            Parameter("max_parts", "query", "number", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter("search", "query", "string", False, None, "A search term."),
        ),
    ),
    "users_sets_create": Operation(
        "POST",
        "/users/{user_token}/sets/",
        ("user_token",),
        (),
        ("set_num", "quantity", "include_spares"),
        ("user_token", "set_num"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("set_num", "formData", "string", True, None, ""),
            Parameter("quantity", "formData", "integer", False, None, ""),
            Parameter("include_spares", "formData", "boolean", False, None, ""),
        ),
    ),
    "users_sets_sync_create": Operation(
        "POST",
        "/users/{user_token}/sets/sync/",
        ("user_token",),
        (),
        ("quantity", "include_spares", "set_num"),
        ("user_token", "set_num"),
        "application/x-www-form-urlencoded",
        (
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("quantity", "formData", "integer", False, None, ""),
            Parameter("include_spares", "formData", "boolean", False, None, ""),
            Parameter("set_num", "formData", "string", True, None, ""),
        ),
    ),
    "users_sets_read": Operation(
        "GET",
        "/users/{user_token}/sets/{set_num}/",
        ("set_num", "user_token"),
        (
            "set_num",
            "theme_id",
            "min_year",
            "max_year",
            "min_parts",
            "max_parts",
            "ordering",
            "search",
        ),
        (),
        ("set_num", "user_token"),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("set_num", "query", "string", False, None, ""),
            Parameter("theme_id", "query", "number", False, None, ""),
            Parameter("min_year", "query", "number", False, None, ""),
            Parameter("max_year", "query", "number", False, None, ""),
            Parameter("min_parts", "query", "number", False, None, ""),
            Parameter("max_parts", "query", "number", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter("search", "query", "string", False, None, "A search term."),
        ),
    ),
    "users_sets_update": Operation(
        "PUT",
        "/users/{user_token}/sets/{set_num}/",
        ("set_num", "user_token"),
        (
            "set_num",
            "theme_id",
            "min_year",
            "max_year",
            "min_parts",
            "max_parts",
            "ordering",
            "search",
        ),
        ("quantity",),
        ("set_num", "user_token"),
        "application/x-www-form-urlencoded",
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("quantity", "formData", "integer", False, None, ""),
            Parameter("set_num", "query", "string", False, None, ""),
            Parameter("theme_id", "query", "number", False, None, ""),
            Parameter("min_year", "query", "number", False, None, ""),
            Parameter("max_year", "query", "number", False, None, ""),
            Parameter("min_parts", "query", "number", False, None, ""),
            Parameter("max_parts", "query", "number", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter("search", "query", "string", False, None, "A search term."),
        ),
    ),
    "users_sets_delete": Operation(
        "DELETE",
        "/users/{user_token}/sets/{set_num}/",
        ("set_num", "user_token"),
        (
            "set_num",
            "theme_id",
            "min_year",
            "max_year",
            "min_parts",
            "max_parts",
            "ordering",
            "search",
        ),
        (),
        ("set_num", "user_token"),
        None,
        (
            Parameter("set_num", "path", "string", True, None, ""),
            Parameter("user_token", "path", "string", True, None, ""),
            Parameter("set_num", "query", "string", False, None, ""),
            Parameter("theme_id", "query", "number", False, None, ""),
            Parameter("min_year", "query", "number", False, None, ""),
            Parameter("max_year", "query", "number", False, None, ""),
            Parameter("min_parts", "query", "number", False, None, ""),
            Parameter("max_parts", "query", "number", False, None, ""),
            Parameter(
                "ordering",
                "query",
                "string",
                False,
                None,
                "Which field to use when ordering the results.",
            ),
            Parameter("search", "query", "string", False, None, "A search term."),
        ),
    ),
}
